### ISSUE TITLE
Add an option to create FileDescriptor from int and vice versa 

### ISSUE THREAD

**Issue by Prototik** [kohlschutter/junixsocket#132]
I'm currently working on transport for dbus-java library with using junixsocket, and faced some minor problem:

dbus-java provides it's own FileDescriptor class (just a wrapper for int), but in order to create it I need to know raw int value of a descriptor. While I can read and write `java.io.FileDescriptor`  from `junixsocket` (with `getReceivedFileDescriptors()` and `setOutboundFileDescriptors()`), I have no way to marshall/demarshall descriptor value itself. Currently `junixsocket` have such functionality in package-private class, so in order to complete my task I wrote such a hack:
```java
package org.newsclub.net.unix;

import java.io.FileDescriptor;
import java.io.IOException;

public class Hack {
    private Hack() {
    }

    public static FileDescriptor createFileDescriptor(int fd) throws IOException {
        NativeUnixSocket.ensureSupported();
        FileDescriptor fileDescriptor = new FileDescriptor();
        NativeUnixSocket.initFD(fileDescriptor, fd);
        return fileDescriptor;
    }

    public static int getFileDescriptor(FileDescriptor fileDescriptor) throws IOException {
        NativeUnixSocket.ensureSupported();
        return NativeUnixSocket.getFD(fileDescriptor);
    }
}
```

It would be great to introduce public API with such capabilities instead.

Thank you in advance.

**Comment by kohlschuetter** [comment]
Hi @Prototik,
thanks for bringing this up!

I've so far deliberately avoided exposing the numeric file descriptor, specifically because Java chose to provide `java.io.FileDescriptor` abstraction as a compromise to handle both Unix-like systems and Windows (the latter usually working with `long` values instead of `int`).

I'm a bit concerned about providing a direct int-to-FileDescriptor method, since that will probably not work as expected in Windows for all sorts of reasons (and I guess that's not really required for your use case).

However, I can see some value in providing access to the raw int value given a `FileDescriptor` object, whenever that's possible — we could provide access to the `int` value through `FileDescriptorCast`:

```
FileDescript fd; // ...
int fdVal = FileDescriptorCast.using(fd).as(Integer.class);
```

**Comment by Prototik** [comment]
FileDescriptionCast for integer a way for converting fds to int, but i need thfe opposite too.

As a alternative I would like to suggest to introduce unsafe socket api to produce/consume int[] instead of FileDescriptor[]
Something like that: ```java
AFUNIXSocket socket = ...;
socket.getReceivedFileDescriptors() // FileDescriptor[]
socket.unsafe().getReceivedFileDescriptors() // int[]
socket.setOutboundFileDescriptors(/* FileDescriptor[] */)
socket.unsafe().setOutboundFileDescriptors(/* int[] */)
```
Such pattern explicitly marks those operations as unsafe and would prefectly fit my use case. Is it looks great?

**Comment by Prototik** [comment]
Yeah, that will work too, just seems a little bit uglier than unsafe socket api, but if it's fine for you - I'm fine too.
Thanks for response.

**Comment by kohlschuetter** [comment]
The advantage of moving this into `FileDescriptorCast` is that this reduces code complexity and improves code auditing.

We would have to duplicate quite some code for the "unsafe()" API approach, whereas here it boils down to making sure that this one function works properly (or is prevented from executing, for example).

Adding this functionality also means we can't just release it in 2.6.3, since the concept of "unsafe" methods is new to junixsocket. I'll have to think about whether this actually is enabled by default (_probably_ yes), and how and where this could be disabled. For now, I think there could be a new `AFSocketCapability` for "unsafe" operations, which also means a System property can guard against their use.

**Comment by kohlschuetter** [comment]
Please verify with the latest 2.7.0-SNAPSHOT. Thanks!

**Comment by Prototik** [comment]
@kohlschuetter sorry for the late response, I'm on vacation now. I migrated from my hack to `FileDescriptorCast` in snapshot version and it works like a charm, thank you.

Waiting for release version to make my PR into dbus-java for a new transport using junixsocket!
