### ISSUE TITLE
Code reusage question

### ISSUE THREAD

**Issue by tommys-place** [kohlschutter/junixsocket#17]
Hi,

I've found your lib very interesting. It would be great feature for implementation in OrientDB database to enable unix socket connections.  I've made rewrite of your C part to Java using JNA lib and keep the rest.

Now, I would like to contribute this modified version to OrientDB opensource database including your code parts. Even if you noted your code as Apache 2.0 license, I would like to ask you for permission to do that. Of course, by keeping your name in code as an original author.

Modified version is here https://github.com/tommys-place/orientdb_unixsocket_driver

**Comment by kohlschuetter** [comment]
Hi tommys-place,

Thanks for using junixsocket.
I haven't fully looked through your code yet, but this one is certainly wrong, "Original author Kohl Schutter". Please check the license requirements, including the NOTICE file.

Ideally, I would of course like to see contributions to junixsocket's codebase. If I understand correctly, your main contribution is using JNA instead of JNI. What if we can extend junixsocket to take either JNI or JNA as the underlying technology? I think this would be very useful.

**Comment by tommys-place** [comment]
Hi,

I fixed license notification in code and added Authors & Notice files. 

Yes, main change is rewrite from JNI part to JNA part. Of course that can be used in junixsocket. Please, feel free to review and give any comment.
